apiVersion: apps/v1
kind: Deployment
metadata:
  name: unit-converter-deployment
  labels:
    app: unit-converter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unit-converter
  template:
    metadata:
      labels:
        app: unit-converter
    spec:
      containers:
      - name: unit-converter
        image: s224748993/unit-converter-app:latest  # yourusername/unit-converter-app:latest (registry)
        imagePullPolicy: Always  # Use "Always" if using a registry
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"