apiVersion: v1
kind: Service
metadata:
  name: unit-converter-service
spec:
  type: NodePort
  selector:
    app: unit-converter
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30005